{
	"version": 1752952309,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/settings-sheet0.png",
		"images/adaptres-sheet0.png",
		"images/settingsicons-sheet0.png",
		"images/phone-sheet0.png",
		"images/phoneicon-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/openanim-sheet0.png",
		"images/iconsmod-sheet0.png",
		"images/weather-sheet0.png",
		"images/weathericon-sheet0.png",
		"images/navbar-sheet0.png",
		"images/appsnames.png",
		"images/wallpaper-sheet0.png",
		"images/dock-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}